name: Spellcheck Action
on: push
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.36.0
      name: Spellcheck
      with:
        source_files: "README.md"
        task_name: Markdown
        config_path: .github/spellcheck.yml
